### ISSUE TITLE
transfer history duplication, why?

### ISSUE THREAD

**Issue by krosza** [Augmint/augmint-core#61]
![image](https://user-images.githubusercontent.com/12797314/33208379-904d7c48-d111-11e7-8426-7697e7a3040f.png)

**Comment by krosza** [comment]
After refresh it is ok, there is only one transfer note

**Comment by szerintedmi** [comment]
this is likely related to a metamask bug: #59

**Comment by szerintedmi** [comment]
hopefully solved with using ethers.js for events
